/* $Id: controller.c,v 1.3 1999/01/09 01:01:52 leslie Exp $ */
/* 
 * Kestrel Run Time Environment 
 * Copyright (C) 1998 Regents of the University of California.
 * 
 * controller.c 
 */

#include "globals.h"
#include "program.h"
#include "format.h"
#include "commands.h"
#include "controller.h"
#include "kdb.h"
#include "queues.h"
#include "getstate.h"
#include "interface.h"

void printControllerMenu(void)
{
  printf( "\n@Main Menu > Controller Menu:\n" );
  printf("\n padqin   - pad input data file in there is insufficient data");
  printf("\n datain   - state of input data queue");
  printf("\n dataout  - data of output data queue");
  printf("\n state    - state of internal controller registers");
  printf("\n menu     - print this menu");
  printf("\n back     - back to the main menu");
  printf("\n quit     - Quit kdb\n\n" );
}

void controller(UserProgram *program)
{
  char *command;
  int command_selection = -1;

  printControllerMenu();
  CurrentMenu = 'c';

  while( command_selection != CNTR_CMD_BACK ) {
    if ((command = GetInput("kdb> ", 1)) == NULL) {
      continue;
    }

    command_selection = InterpretInput(command);
    switch( command_selection ) {
    case CNTR_CMD_DATAIN :
      displayDataInStatus(program);
      break;
    case CNTR_CMD_DATAOUT :
      displayDataOutStatus(program);
      break;
    case CNTR_CMD_QINPAD :
      program->input_qinpad = 1;
      ScreenPrint("Input Data will be padded with zeros.\n");
      break;
    case CNTR_CMD_STATE :
      displayControllerState(program);
      break;
    case CNTR_CMD_MENU :
      printControllerMenu();
      break;
    case CNTR_CMD_QUIT :
      QuitKdb();
      break;
    case CNTR_CMD_BACK :
      break;
    default:
      printf( "Invalid command. Type 'menu' for a list of commands\n");
      break;
    }
  }

  lastMenu = CurrentMenu;
}


void displayDataInStatus(UserProgram *program)
{
  int byte_count;
  
  FlushQueues(program);

  /*printf("NEEDS WORK FOR MULTIPLE FILES\n"); */

  printf("Number of input files: %d  Total Bytes: %d\n",
	 program->numInputData, program->input_total);
  if (program->currentInputIndex >= program->numInputData) {
    printf("input is used up.\n");
  } else {
    printf("Current input is (%d): %s  numBytes: %d\n",
	 program->currentInputIndex+1,
         program->inputData[program->currentInputIndex].input_fileName,
         program->inputData[program->currentInputIndex].input_total);

    printf("Bytes read from file: %d  Bytes written to board: %d\n",
	 program->inputData[program->currentInputIndex].input_position,
         program->input_writeBoard);
  }
  if (program->input_padbytes == 0) {
    if (program->input_numQinBytes) {
      byte_count = program->input_writeBoard - program->input_numQinBytes;
      if (program->input_gaveLastByte) {
	byte_count++;
      }
    } else {
      byte_count = program->input_writeBoard;
    }
  } else {
    byte_count = program->input_total + 
      (program->input_padbytes - program->input_numQinBytes);
    if (program->input_gaveLastByte && program->state != PROGRAM_STATE_DONE) {
      byte_count++;
    }
  }

  printf("Bytes read by controller: %d \n", byte_count);
  if (program->input_gaveLastByte || byte_count >= program->input_total) {
    printf("Program has used all input data.\n");
  }

}

void displayDataOutStatus(UserProgram *program)
{
  FlushQueues(program);

  printf("Output file name: %s  Bytes written: %d\n", 
	 program->output_fileName, program->output_bytesWritten);
  printf("Total bytes generated by kestrel program: %d\n",
	 program->output_bytesWritten + program->output_last);
}

void displayControllerState(UserProgram *program)
{
  if (program->controller_current == 0) {
    SaveControllerState(program);
    RestoreControllerState(program);
  }

  printf("PC: %d\n", program->cntr_state->pc);
  printf("PC Stack Elelemts: %d  Counter Stack Elements: %d\n",
	 program->cntr_state->pcstack_el,
	 program->cntr_state->cntrstack_el);
  printf("Scratch Register: %d  CBS (WOR): %d\n",
	 program->cntr_state->scratch,
	 program->cntr_state->cbs);
}

/* end of program 'controller.c' */
